# Application Name
spring.application.name=${SPRING_APPLICATION_NAME}

#server.address=0.0.0.0



# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}



# JPA Configuration
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql


# Server Port
server.port=${SERVER_PORT}


# Abilitare SSL
#server.ssl.enabled=false

# Percorso del keystore (assicurati che il file keystore.p12 si trovi nella cartella delle risorse del progetto)
#server.ssl.key-store=classpath:keystore.p12

# Password del keystore
#server.ssl.key-store-password=Jhonnyxvendetta

# Tipo del keystore (PKCS12 è molto comune)
#server.ssl.key-store-type=PKCS12










#spring.application.name=copio

#server.address=0.0.0.0



# Database Configuration
#spring.datasource.url=jdbc:postgresql://localhost:5432/copio_db
#spring.datasource.username=copio
#spring.datasource.password=copiox123
#spring.datasource.driver-class-name=org.postgresql.Driver



# JPA Configuration
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.sql.init.mode=always
#spring.sql.init.schema-locations=classpath:schema.sql


# Server Port
#server.port=9000


# Abilitare SSL
server.ssl.enabled=true

# Percorso del keystore (assicurati che il file keystore.p12 si trovi nella cartella delle risorse del progetto)
server.ssl.key-store=classpath:keystore.p12

# Password del keystore
server.ssl.key-store-password=Jhonnyxvendetta

# Tipo del keystore (PKCS12 è molto comune)
server.ssl.key-store-type=PKCS12

# Logging per le richieste HTTP CORS
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=DEBUG
logging.level.org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver=DEBUG

# Log completo delle richieste HTTP
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=TRACE

# Log di Spring Security (se usato)
logging.level.org.springframework.security=DEBUG