spring.application.name=copio
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/copio_db
spring.datasource.username=copio
spring.datasource.password=copiox123
spring.jpa.show-sql: true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.format_sql=true


