# Usa l'immagine ufficiale di Node.js per costruire l'app
FROM node:18 AS build

# Imposta la directory di lavoro
WORKDIR /app

# Copia i file package.json e package-lock.json
COPY package*.json ./

# Installa le dipendenze dell'app
RUN npm install --legacy-peer-deps

# Copia il codice sorgente dell'app Angular
COPY . .

# Costruisci l'app Angular in modalità produzione
RUN npm run build --prod

