server {
    listen 3001;
    server_name copio.online www.copio.online;

    location / {
        proxy_pass http://frontend:3000;  # Porta del frontend
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 80;
    server_name copio.online www.copio.online;

    location / {
        return 301 http://copio.online:3000;  # Redirige da 80 a 3000
    }
}

